// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxDt7iArosVtZDnOURLbqej_OoWCK3KSc',
    appId: '1:860023661375:web:5540f1ee45c010deb3a98a',
    messagingSenderId: '860023661375',
    projectId: 'tpdevmobile-16309',
    authDomain: 'tpdevmobile-16309.firebaseapp.com',
    storageBucket: 'tpdevmobile-16309.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOlB9zWaZG66zDi32-bdZFVKRHg5Idgdo',
    appId: '1:860023661375:android:c4a2ec26543a10ddb3a98a',
    messagingSenderId: '860023661375',
    projectId: 'tpdevmobile-16309',
    storageBucket: 'tpdevmobile-16309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhp4NAhoGOKvMTLigZHQhxwTlQdOWIoBU',
    appId: '1:860023661375:ios:78041ccade9af03ab3a98a',
    messagingSenderId: '860023661375',
    projectId: 'tpdevmobile-16309',
    storageBucket: 'tpdevmobile-16309.appspot.com',
    iosBundleId: 'com.example.tpDevMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhp4NAhoGOKvMTLigZHQhxwTlQdOWIoBU',
    appId: '1:860023661375:ios:735c60ae8a5ae8acb3a98a',
    messagingSenderId: '860023661375',
    projectId: 'tpdevmobile-16309',
    storageBucket: 'tpdevmobile-16309.appspot.com',
    iosBundleId: 'com.example.tpDevMobile.RunnerTests',
  );
}
